apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1
  labels:
    app: app-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-v1
  template:
    metadata:
      labels:
        app: app-v1
    spec:
      containers:
      - name: sample-ctr
        image: sravanmarolix/ems:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc1
  labels:
      app: app-v1
spec:
  selector:
    app: app-v1
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer

